---
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

services:
  - mysql

cache:
 directories:
   - $HOME/.composer/cache

before-install:
 - composer self-update
 - sudo apt-get -y install git

install:
  - composer install --dev

script:
  - vendor/bin/phpunit
